# SConscript file which can be included from a top-level SConsctuct file.
# Provides a static library called 'telemetry'.
#
# Usage:
# telemetry = SConscript('telemetry/server-cpp/SConscript', exports='env')
# Read up on SCons hierarchical builds for more information.
#
# Inputs:
# - env: properly configured C++ build environment for your platform (like
#   env['CXX'] = 'arm-none-eabi-g++').
# - telemetry_paths: additional paths (absolute directory) that telemetry needs
#   (like platform header files).
#
# Returns:
# - a static library to be included in your program

Import('env', 'telemetry_paths')

env = env.Clone()

env.Append(CPPPATH = ['.', telemetry_paths])

lib = env.StaticLibrary('telemetry', Glob('*.cpp'))

Return('lib')
